# .github/workflows/ci.yml

name: CI/CD Pipeline for Data parsing to Google Sheets

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  data-checkout:
    runs-on: ubuntu-latest
    
    steps:
      # Krok 1: Checkout repozytorium
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'


      - name: Install all dependencies
        run: |
          pip install -r requirements.txt 

#      - name: Upload file to Google Sheets
#        run: |
#            python fetch_data.py
           

      - name: Clean and process data
        run: |
          python feature_engee.py

      - name: Data Training and Testing
        run: |
          python model_training.py

      # Krok 6: Wyświetlanie raportu z procesu czyszczenia danych
      - name: Display Report
        run: |
          cat report.txt

      # Krok 7: Wyświetlanie logów (opcjonalne, do debugowania)
      - name: Display Log
        run: |
          cat data_processing.log
      - name: Display Log
        run: |
          cat logs.txt
          

 

